### ISSUE TITLE
'iminuit._libiminuit.Minuit' has no attribute 'from_array_func'

### ISSUE THREAD

**Issue by proscrite** [iminuit/iminuit#290]
Hello, noob question:
I'm trying to minimize a function with a variable number of parameters and it seems libiminuit does not contain any attribute 'from_array_func'

```
AttributeError: type object 'iminuit._libiminuit.Minuit' has no attribute 'from_array_func'
```
I checked the directory where _libiminuit.pyx should be and instead of it the file I find (and cannot open) is _libiminuit.cpython-36m-x86_64-linux-gnu.so
I tried reinstalling iminuit both from conda and pip but it did not solve the issue. I'm working with Ubuntu 14.04, python3.6.6, pip 10.0.1 and conda 4.5.10.
Also please excuse me if I didn't formulate the question correctly or in the right place.
Thanks!

**Comment by cdeil** [comment]
Can you please paste the full error traceback?

What do you get here?
(i.e. are you using the Python / iminuit you thing you're using?
```
python -c 'import iminuit; print(iminuit)'
python -c 'import iminuit; print(iminuit.__version__)'
```

`from_array_func` was added in iminuit 1.3

**Comment by proscrite** [comment]
Yer, apparently I'm in the outdated version:
```
python -c 'import iminuit; print(iminuit)'
<module 'iminuit' from '~/anaconda3/lib/python3.6/site-packages/iminuit/__init__.py'>
python -c 'import iminuit; print(iminuit.__version__)'
1.2
```
I will try to update it. Cheers!

**Comment by cdeil** [comment]
Try `pip install -U iminuit`, that should give you v1.3.2 and have this working.

Closing issue. Please re-open or file a new one if you find an issue.

**Comment by NuclearDestruction** [comment]
Hello, I have tried using minuit for minimization purposes on a multi-parameters function but what I get (in jupyter notebook and in python3 shell) is: AttributeError: type object 'Minuit' has no attribute 'from_array_func'.
Could you please guide me in solving this issue? 
I have tried the instruction you gave in the previous comment, but it didn't work.

**Comment by mbirman6** [comment]
See changelog for version 2.0:
"Minuit.from_array_func was removed; use Minuit(some_numpy_function, starting_array) instead"
